# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dragon_diffusion',
                'doc_host': 'https://stroopwafl.github.io',
                'git_url': 'https://github.com/stroopwafl/dragon_diffusion',
                'lib_path': 'dragon_diffusion'},
  'syms': {'dragon_diffusion.core': {'dragon_diffusion.core.foo': ('core.html#foo', 'dragon_diffusion/core.py')}}}
